IF OBJECT_ID('SP_CATEGORY_SETUP') IS NOT NULL
DROP PROCEDURE SP_CATEGORY_SETUP
GO
CREATE PROCEDURE SP_CATEGORY_SETUP
@FLAG CHAR,
@ID INT=NULL,
@NAME NVARCHAR(100)=NULL,
@PARENTID INT=NULL,
@LEVELS INT=NULL,
@ICON NVARCHAR(600)=NULL,
@ISACTIVE BIT=0,
@UserID NVARCHAR(MAX)=NULL
AS
BEGIN
	DECLARE @MSG NVARCHAR(MAX)
	IF @FLAG='S'-----for gridshow
	BEGIN
		SELECT C.ID,C.Name,C1.[NAME] Parent, C.ParentID,C.Levels,C.Icon,CONVERT(NVARCHAR, C.CreatedDate, 103) CreatedDate, U.FullName CreatedBy,C.Active
		FROM Category C WITH(NOLOCK)
		LEFT JOIN Category C1 WITH(NOLOCK) ON C.ParentID=C1.ID
		LEFT JOIN Users U WITH(NOLOCK) ON U.ID=C.CreatedBy
	END
	IF @FLAG='D'------FOR DELETE DATA
	BEGIN
	BEGIN TRY
		BEGIN TRAN
		DELETE FROM Category WHERE ID = @ID 
		COMMIT TRAN
		SELECT 'RECORD DELETE SUCCESSFULLY.' MSG
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN 
		SET @MSG= CONCAT('Log Line: ', CAST(SCOPE_IDENTITY() AS NVARCHAR(10)), ', Error Line: ' , CAST(ERROR_LINE() AS NVARCHAR(10)), ', MSG: ', ERROR_MESSAGE())
		;THROW 51002, @MSG, 1;
		RETURN
	END CATCH
	END
	IF @FLAG='U'-----FOR UPDATE
	BEGIN
	BEGIN TRY
	BEGIN TRAN
		UPDATE Category
		SET NAME=@NAME,
			ParentID=@PARENTID,
			Levels=@LEVELS,
			Active=@ISACTIVE,
			Icon=ISNULL(@ICON, ICON)
		WHERE ID=@ID
		COMMIT TRAN
		SELECT 'RECORD UPDATED SUCCESSFULLY.' MSG
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN 
		SET @MSG= CONCAT('Log Line: ', CAST(SCOPE_IDENTITY() AS NVARCHAR(10)), ', Error Line: ' , CAST(ERROR_LINE() AS NVARCHAR(10)), ', MSG: ', ERROR_MESSAGE())
		;THROW 51002, @MSG, 1;
		RETURN
	END CATCH
	END
	IF @FLAG='I'----FOR SAVE	
	BEGIN
	BEGIN TRY
		BEGIN TRAN
			INSERT INTO Category([NAME],ParentID,Levels,Icon,CreatedBy,Active)
			VALUES (@NAME,@PARENTID,@LEVELS,@ICON,@UserID,@ISACTIVE)
		COMMIT TRAN
		SELECT 'RECORD SAVED SUCCESSFULLY.' MSG
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN 
		SET @MSG= CONCAT('Log Line: ', CAST(SCOPE_IDENTITY() AS NVARCHAR(10)), ', Error Line: ' , CAST(ERROR_LINE() AS NVARCHAR(10)), ', MSG: ', ERROR_MESSAGE())
		;THROW 51002, @MSG, 1;
		RETURN
	END CATCH
	END
	IF @FLAG='E'----FOR EDIT
	BEGIN
		SELECT C.ID,C.Name,C.ParentID,C.Levels,C.Icon,CONVERT(NVARCHAR, C.CreatedDate, 103),C.CreatedBy,C.Active
		FROM Category C WITH(NOLOCK)
		Where ID=@ID
	END
END
