IF OBJECT_ID('SP_CATEGORIES') IS NOT NULL
DROP PROCEDURE SP_CATEGORIES
GO
CREATE PROCEDURE SP_CATEGORIES
(
	@FLAG CHAR
)
AS
BEGIN
	IF @FLAG='S'-----for CATEGORY PAGE
	BEGIN
		SELECT    C.[Name], C.[Icon], C.[ID] FROM Category C WITH(NOLOCK) 
	END
END