IF OBJECT_ID('SP_DASHBOARD') IS NOT NULL
DROP PROCEDURE SP_DASHBOARD
GO
CREATE PROCEDURE SP_DASHBOARD
(
	@FLAG CHAR
)
AS
BEGIN
IF @FLAG='A'
BEGIN
	SELECT 
		ISNULL((
				SELECT COUNT(*) FROM Users U WITH(NOLOCK) 
				JOIN UserRoles UR WITH(NOLOCK)  ON U.Id=UR.UserId
				JOIN Roles R WITH(NOLOCK) ON UR.RoleId=R.Id
				WHERE R.Name='User' AND ISNULL(U.Active, 0)=1
		), 0) TOTAL_USERS,
		ISNULL((
				SELECT COUNT(*) FROM Products P WITH(NOLOCK) 
				WHERE ISNULL(P.Active, 0)=1
		), 0) TOTAL_PRODUCTS,
		ISNULL((
				SELECT COUNT(*) FROM Orders O WITH(NOLOCK) 
				WHERE-- ISNULL(O.StatusID, 0)=1 AND 
				CAST(O.OrderedDate AS DATE) = CAST(GETDATE() AS DATE)
		), 0) TOTAL_ORDERS_TODAY,
		ISNULL((
				SELECT COUNT(*) FROM Orders O WITH(NOLOCK) 
				WHERE --ISNULL(O.StatusID, 0)=1 AND 
				CAST(O.OrderedDate AS DATE) BETWEEN DATEADD(DAY, 1, DATEADD(MONTH, -1, EOMONTH(GETDATE())))  AND CAST(GETDATE() AS DATE)
		), 0) TOTAL_ORDERS_MONTH
END
IF @FLAG='V'--- Pie , GetOrderStatusThisMonth
BEGIN
	SELECT * FROM (
		SELECT O.StatusID, S.[Name], COUNT('') COUNTS 
		FROM Orders O WITH(NOLOCK)
		JOIN OrderStatus S WITH(NOLOCK) ON O.StatusID = S.ID
		WHERE CAST(O.OrderedDate AS DATE) BETWEEN DATEADD(DAY, 1, DATEADD(MONTH, -1, EOMONTH(GETDATE())))  AND CAST(GETDATE() AS DATE)
		GROUP BY StatusID, S.[Name]
	) T
	PIVOT
	(
		COUNT(COUNTS) FOR [Name] IN (Ongoing, Cancelled, Delivered,Refund)
	) P
	ORDER BY StatusID
END
IF @FLAG='Y'--- GRAPH , GetOrdersThisMonth
BEGIN
	SELECT OrderedDate [Date],  COUNT('') COUNTS 
	FROM Orders O WITH(NOLOCK) 
	WHERE ISNULL(O.StatusID, 0) IN (1, 3) 
	AND CAST(O.OrderedDate AS DATE) BETWEEN DATEADD(DAY, 1, DATEADD(MONTH, -1, EOMONTH(GETDATE())))  AND CAST(GETDATE() AS DATE)
	GROUP BY OrderedDate
	ORDER BY OrderedDate
END
IF @FLAG='Z'--- GRAPH , GetNewUsersThisMonth
BEGIN
	SELECT U.DateCreated [Date],  COUNT('') COUNTS 
	FROM Users U WITH(NOLOCK) 
	JOIN UserRoles UR WITH(NOLOCK)  ON U.Id=UR.UserId
	JOIN Roles R WITH(NOLOCK) ON UR.RoleId=R.Id
	WHERE R.Name='User' AND ISNULL(U.Active, 0)=1
		AND CAST(U.DateCreated AS DATE) BETWEEN DATEADD(DAY, 1, DATEADD(MONTH, -1, EOMONTH(GETDATE())))  AND CAST(GETDATE() AS DATE)
	GROUP BY U.DateCreated
	ORDER BY U.DateCreated
END
END