IF OBJECT_ID('SP_VIEW_ORDER') IS NOT NULL
DROP PROCEDURE SP_VIEW_ORDER
GO
CREATE PROCEDURE SP_VIEW_ORDER
(
	@FLAG CHAR,
	@FROMDATE DATETIME=NULL,
	@TODATE DATETIME=NULL,
	@USERID NVARCHAR(100)=-1,
	@STATUS NVARCHAR(100)=-1
)
AS
BEGIN
	IF @FLAG='S'-----for gridshow
	BEGIN
		SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL))SN,U.FullName,U.Address,PAIDMETHOD
		,GRANDTOTAL,OrderedDate,ISPAID,PAIDDATE,DELIVERYDATE,U.PhoneNumber,RS.NAME AS STATUS
		FROM ORDERS R WITH(NOLOCK)
		LEFT JOIN USERS U WITH(NOLOCK) ON R.UserID=U.Id
		LEFT JOIN OrderStatus RS WITH(NOLOCK) ON R.StatusID=RS.ID
		WHERE CAST(OrderedDate AS DATE) BETWEEN @FROMDATE AND @TODATE
		AND  1= CASE 
					WHEN @USERID=-1 THEN 1
					WHEN R.UserID = @USERID THEN 1
					ELSE 0
				END
		AND  1= CASE 
					WHEN @STATUS=-1 THEN 1
					WHEN R.StatusID = @STATUS THEN 1
					ELSE 0
		END
	END
	
END
